import { Inter } from "next/font/google";
import "./globals.css";
import { CitasProvider } from "@/context/citas";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "tp6-citas-next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href={inter.url} />
        <link href="https://fonts.googleapis.com/css?family=Staatliches" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" />
      </head>
      <body className={inter.className}>
        <Navbar/>
        <CitasProvider>
          {children}
        </CitasProvider>
      </body>
    </html>
  );
}
